### ISSUE TITLE
Create Partitions Script: Add Missing Tables and Correct Check for Partition Already Exists

### ISSUE THREAD

**Issue by djw4erg** [US-EPA-CAMD/easey-db-scripts#12]
The CAMDDMW.CREATE_PARTITIONS procedure exists to create partitions for tables where  the partitions are based on year (or time).  Add missing tables and correct the checking for an existing partitions before creating a new partition.

Currently the procedure attempts to determine whether a partition has already been created based on the partition name.  However while some of the partition names include the year of the partition, others also include the year and week, and the most problematic only include a numeric index.

1. Ensure the current check existence logic for tables with Year and Week in the partition names works.
2. Determine whether to change tables that use numeric indexes in the partition names should either switch to using Year with, if needed, other values in the partition names to allow use of the partition name to determine whether a partition has been created.  Essentially, the partition name would indicate the time period (with the year) that the partition contains.  The other option is to attempt to use catalog information to determine what time period each partition contains.
3. Make the changes to the procedure for each table that needs changes.
4. Determine whether transition partition names are needed for any table, and if so manually create those partitions for the next year.

**Missing Tables**:

- ALLOWANCE_HOLDING_DIM: Should create partitions for 30 years in the future, so when creating partitions for 2024, create partitions out to 2054.
- REP_YEAR_DIM
 
**Currently Handled Tables**:

- ANNUAL_UNIT_DATA
- CONTROL_YEAR_DIM
- DAY_UNIT_DATA
- FUEL_YEAR_DIM
- HOUR_UNIT_DATA
- HOUR_UNIT_MATS_DATA
- MONTH_UNIT_DATA
- OZONE_UNIT_DATA
- PROGRAM_YEAR_DIM
- QUARTER_UNIT_DATA
- UNIT_FACT
- UNIT_TYPE_YEAR_DIM

**Comment by alangmaid** [comment]
Closed because I recreated it in EASEY-UI
